"""
Base detection rule interface
"""
from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional
from dataclasses import dataclass

@dataclass
class Alert:
    rule_name: str
    severity: str
    message: str
    packet_index: int
    timestamp: float
    metadata: Dict[str, Any]
    
    def __str__(self):
        return f"[{self.severity}] {self.rule_name}: {self.message}"

class BaseRule(ABC):
    def __init__(self, name: str, severity: str = "MEDIUM"):
        self.name = name
        self.severity = severity
        self.enabled = True
        self.alerts: List[Alert] = []
        self.stats = {
            'packets_analyzed': 0,
            'alerts_generated': 0
        }
    
    @abstractmethod
    def analyze(self, context: Dict[str, Any]) -> List[Alert]:
        """
        Analyze traffic and generate alerts
        Args:
            context: Dictionary with packets, flows, metadata
        Returns:
            List of Alert objects
        """
        pass
    
    def create_alert(self, message: str, packet_index: int, timestamp: float, metadata: Optional[Dict[str, Any]] = None) -> Alert:
        """Create an alert"""
        alert = Alert(
            rule_name=self.name,
            severity=self.severity,
            message=message,
            packet_index=packet_index,
            timestamp=timestamp,
            metadata=metadata or {}
        )
        self.alerts.append(alert)
        self.stats['alerts_generated'] += 1
        return alert
    
    def get_alerts(self) -> List[Alert]:
        """Get all alerts generated by this rule"""
        return self.alerts
    
    def clear_alerts(self):
        """Clear all alerts"""
        self.alerts.clear()
    
    def enable(self):
        """Enable rule"""
        self.enabled = True
    
    def disable(self):
        """Disable rule"""
        self.enabled = False
    
    def get_stats(self) -> Dict[str, Any]:
        """Get rule statistics"""
        return {
            'name': self.name,
            'severity': self.severity,
            'enabled': self.enabled,
            **self.stats
        }